### ISSUE TITLE
Moving calendar entry via drag and drop causes 500 

### ISSUE THREAD

**Issue by haslinger** [refugeeHackVienna/iamin#17]
Seen this on staging.

**Comment by haslinger** [comment]
Error dump:
```
I, [2015-10-20T09:26:16.165158 #32208]  INFO -- : 
Sent mail to  (3.1ms)
E, [2015-10-20T09:26:16.165708 #32208] ERROR -- : Actor crashed!
ArgumentError: An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.
	/home/rails/.rvm/gems/ruby-2.1.5/gems/mail-2.6.3/lib/mail/check_delivery_params.rb:9:in `check_delivery_params'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/actionmailer-4.2.4/lib/action_mailer/base.rb:543:in `block in deliver_mail'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/actionmailer-4.2.4/lib/action_mailer/base.rb:541:in `deliver_mail'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/actionmailer-4.2.4/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/actionmailer-4.2.4/lib/action_mailer/message_delivery.rb:105:in `deliver'
	/var/rails/where2help/app/jobs/notify_job.rb:5:in `perform'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	(celluloid):0:in `remote procedure call'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/rails/.rvm/gems/ruby-2.1.5/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
I, [2015-10-20T09:26:16.167228 #32208]  INFO -- : Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.6ms)
F, [2015-10-20T09:26:16.169232 #32208] FATAL -- : 
ArgumentError (An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.):
  app/jobs/notify_job.rb:5:in `perform'
  app/controllers/api/calendar/needs_controller.rb:33:in `update'

```

**Comment by ramonh** [comment]
I've seen this on Heroku as well. I'll look into it

**Comment by klappradla** [comment]
@ramonh check [this line](https://github.com/refugeeHackVienna/iamin/blob/master/app/mailers/volunteer_mailer.rb#L8). The mailer is always triggered, even if there are no users volunteering yet (and therefore no email addresses to send the respective email to).

**Comment by ramonh** [comment]
Right, makes sense. I'll clean this up. Thank you @klappradla

**Comment by haslinger** [comment]
Pulled to staging. Tested. Works. Well done!

**Comment by ramonh** [comment]
Oh ok so 76271db84905ba4fe1a7ee281daf9a686c9d9220 fixed it :+1:  Great!

**Comment by haslinger** [comment]
Yep.
